"""initial schema

Revision ID: eb8755c4479a
Revises: 
Create Date: 2026-06-12 00:32:04.270046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8755c4479a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(), nullable=False),
    sa.Column('controla_lote', sa.Boolean(), nullable=False),
    sa.Column('controla_validade', sa.Boolean(), nullable=False),
    sa.Column('controla_serie', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('localizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposito_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['deposito_id'], ['depositos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposito_id', 'codigo', name='uq_localizacao_deposito_codigo')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentacao'), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'localizacao_id', name='uq_saldo_produto_localizacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos_estoque')
    op.drop_table('movimentacoes')
    op.drop_table('localizacoes')
    op.drop_table('usuarios')
    op.drop_table('produtos')
    op.drop_table('depositos')
    # ### end Alembic commands ###
